version: "3.8"

services:
  comfyscripting:
    image: seanstrcairns/comfyscripting
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: comfyscripting
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8188:8188"  # ComfyUI
    volumes:
      - "./models:/opt/comfyui/models:rw"
      - "./custom_nodes:/opt/comfyui/custom_nodes:rw"
    deploy:
      resources:
        reservations:
          devices:
          - driver: cdi
            capabilities:
              - gpu
            device_ids:
              - nvidia.com/gpu=all