version: '3.8'

services:
  vscode:
    build: .
    container_name: vscode-server
    ports:
      - "8080:8080"
    environment:
      - PASSWORD=changeme  # 🔐 Change this in production!
    volumes:
      - ./project:/home/coder/project  # Mount local ./project to container
    restart: unless-stopped
